# Generated by Django 4.0.4 on 2023-01-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='title',
            new_name='name',
        ),
    ]
